name: Feature Request
description: Suggest a new feature or enhancement for Synapse
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New AI Integration (e.g., OpenAI, Claude)
        - User Interface Improvement
        - Voice/Audio Enhancement
        - Clipboard Functionality
        - Hotkey/Keyboard Shortcuts
        - Configuration/Settings
        - Performance Improvement
        - Cross-platform Support
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature you want to see added...
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: This feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working? What would the user experience look like?
      placeholder: The feature could work by...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Alternative approaches could include...

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with Synapse's goal of seamless AI assistance
          required: true
        - label: I would be willing to help test this feature when available
          required: false